name: Release Build
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Snapshot & Publish to Registry
        uses: jen20/action-docker-build@v1
        with:
          repository: jen20/pulumi-build-container
          username: jen20
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tag-latest: true
